name: Saurav says hi
on: push
jobs:
  perform_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print greetings by github
        run: echo "Hello from GitHub Actions! from ubuntu"

      - name: Run multiple commands
        run: |
          echo "Step 1"
          node -v
          npm -v
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
